function value = bilininterp(z1,y1,V,z1star,y1star)

% input equally spaced coordinate matrices generated by meshgrid of x and y
% input the data z and input the coordinate xstar and
% ystar where you want the value, returns z bilinearly
% interpolated to (xstar,ystar)
% V is the data
%%TEST MATERIAL
%y1 = -1:.1:1;
%z1 = -1:.1:0;
%z1star = -.12;
%y1star = -.56;
%cos(y1star)*sin(z1star)
%%
y = y1;
z = z1;
zstar = z1star;
ystar = y1star;
Ystar = y(length(y)) - y(1);
Zstar = z(length(z)) - z(1);

if y(1) < 0
    ystar = ystar - y(1);
    y = y - y(1);
end

if z(1) < 0
    zstar = zstar - z(1);
    z = z - z(1);
end

cellz = (zstar/Zstar)*(length(z) - 1) + 1;
celly = (ystar/Ystar)*(length(y) - 1) + 1;
cellz_R = mod(cellz,1);
celly_R = mod(celly,1);
cellz = floor(cellz);
celly = floor(celly);
v_c = zeros(2,2);

v_c(1,1) = V(cellz,celly);
v_c(1,2) = V(cellz,celly+1);
v_c(2,1) = V(cellz + 1,celly);
v_c(2,2) = V(cellz +1,celly + 1);
weighty = [1-celly_R celly_R];
weightz = [1-cellz_R cellz_R];

value = (v_c(1,1)*weighty(1) + v_c(1,2)*weighty(2))*weightz(1) + (v_c(2,1)*weighty(1) + v_c(2,2)*weighty(2))*weightz(2);

end